### ISSUE TITLE
Búsqueda de librerías o implementación propia del algoritmo

### ISSUE THREAD

**Issue by gaston-23** [Juanma1223/ia-uncuyo-2021#13]
- Investigar TensorFlow

- Investigar SciKit

- Otras

- Compararlas para saber cual se ajusta mejor a nuestras necesidades

**Comment by Juanma1223** [comment]
En este punto tenemos que realizar una implementación de Q-Learning y encontrar una implementación de Deep Reinforcement Learning usando TensorFlow
