### ISSUE TITLE
Anteproyecto: Mencionar forma de evaluacion (metricas)

### ISSUE THREAD

**Issue by harpomaxx** [Juanma1223/ia-uncuyo-2021#4]
Como se va a evaluar el resultado del algoritmo. Como se lo va a comparar con otro?
Por ejemplo, se va a evaluar el tiempo de ejecución, la cantidad de veces que llega a un estado objetivo, la tasa de observaciones correctamente detectadas, etc.

**Comment by harpomaxx** [comment]
Importante: yo tomaria primero un algoritmo simple de implementar como Q-Learning (pueden usar bibliotecas) y luego le exigiria al maximo. Quizas complicando el escenario con obastaculos, o con dos snakes. Y mediriia la performance frente a los distintos escenarios.

**Comment by harpomaxx** [comment]
Luego, (si llegan y tienen tiempo) podemos evaluar DQN o algun otro algoritmo de Deep RL

**Comment by gaston-23** [comment]
Solucionado, se medira segun tiempo de respuesta para alcanzar una misma puntuacion (eficiencia), puntuacion maxima alcanzada y performance ante distintos escenarios
